#
###################################
# Site wide configuration
####################################
#
title: Arszilla
email: arszilla@outlook.com
description: Mathematics undergrad doing pentesting & malware analysis.
url: https://arszilla.com
baseurl: ""
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Turkey
markdown:          kramdown
highlighter:       rouge
permalink:         /:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Arszilla
  avatar: avatar.jpg
  job: "Student"
  bio: "Mathematics undergrad doing pentesting & malware analysis"
  email: arszilla@outlook.com
  twitter: Arszilla
  google:
    analytics: UA-147415223-1
  github: Arszilla
  linkedin: arslanmasood